-- Create client_leads table to store leads generated BY the agency's clients
CREATE TABLE IF NOT EXISTS public.client_leads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    business_slug TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    customer_email TEXT,
    message TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: We'll link business_slug to personalized_previews in the backend logic instead of strict FK for flexibility
